### ISSUE TITLE
Cutover from Dockerhub

### ISSUE THREAD

**Issue by thelamer** [linuxserver/docker-templates#218]
New rate limits go into effect Nov 2nd. See parent issue: 
https://github.com/linuxserver/docker-jenkins-builder/issues/68

All the templates in this repo need to use the Github endpoint instead of dockerhub, unraid users do a pull to detect new versions this will block them almost instantly on Dockerhub.

**Comment by Roxedus** [comment]
I 100% agree to this. But I do need to add a disclaimer that the Unraid GUI complains on other registries. It will say `not available` regarding updates, so that will more than likely raise some support questions.

Example:
![image](https://user-images.githubusercontent.com/7110194/97783633-6b5aef80-1b99-11eb-8a81-d549bd03590a.png)
